version: "3"

networks:
  my_network:
    driver: bridge

  
services:
    mongo1:
        image: mongo:5
        container_name: mongo1
        networks:
          - my_network
        command: ["mongod", "--replSet", "rs0"]
        ports:
            - 27011:27017
        healthcheck:
            test: test $$(echo "rs.initiate({_id:'rs0',members:[{_id:0,host:\"192.168.22.140:27011\"},{_id:1,host:\"192.168.22.140:27012\"},{_id:2,host:\"192.168.22.140:27013\"}]}).ok || rs.status().ok" | mongo --port 27017 --quiet) -eq 1
            interval: 10s
            start_period: 30s
        volumes:
            - './dataprod1:/data/db'
            - './scripts:/scripts'
        depends_on:
            - mongo2
            - mongo3

    mongo2:
        image: mongo:5
        container_name: mongo2
        networks:
          - my_network
        command: ["mongod", "--replSet", "rs0"]
        ports:
            - 27012:27017
        volumes:
            - './dataprod2:/data/db'

    mongo3:
        image: mongo:5
        container_name: mongo3
        networks:
          - my_network
        command: ["mongod", "--replSet", "rs0"]
        ports:
            - 27013:27017
        volumes:
            - './dataprod3:/data/db'

    mongosetup:
        image: mongo:5
        container_name: mongodb_va
        networks:
          - my_network
        depends_on:
            - mongo1
            - mongo2
            - mongo3
        restart: "no"
        command: >
            mongo --host 192.168.22.140:27011 --eval
            '
            var config = {
                "_id" : "rs0",
                "members" : [
                    {
                        "_id" : 0,
                        "host" : "192.168.22.140:27011"
                    },
                    {
                        "_id" : 1,
                        "host" : "192.168.22.140:27012"
                    },
                    {
                        "_id" : 2,
                        "host" : "192.168.22.140:27013"
                    }
                ]
            };
            rs.initiate(config);
            '
